<h3>Categorias</h3>

<p><a href="?edit=0">Adicionar</a><br></p>

{if $edit >= 0}
<form method="post">
    <label>Nome: <input type="text" name="data[nome]" value="{$categoria.nome}"></label>
    <label><input type="submit" name="submit" value="Salvar" style="width: 60px;"></label>
    <input type="hidden" name="id" value="{$edit}">
</form>

<div class="clearfix"></div>

{/if}

<table>
    <thead>
        <tr>
            <th style="width: 5%;">ID</th>
            <th>Nome</th>
            <th style="width: 100px;">Ação</th>
        </tr>
    </thead>
    <tbody>
        {section name=i loop=$categorias}
        <tr>
            <td>{$categorias[i].id}</td>
            <td>{$categorias[i].nome}</td>
            <td>
                <a href="?edit={$categorias[i].id}"><img src="images/icons/edit.png"></a>
                &nbsp;
                <a href="?delete={$categorias[i].id}"><img src="images/icons/delete.png"></a>
            </td>
        </tr>
        {/section}
    </tbody>
</table>
