{if !$pedido_id}
<h3>Efetuar compra</h3>
<br>
<p><b>Produto: </b> {$produto.nome}</p>
<br>
<img src="https://www.moip.com.br/moiplabs/logo_moip.png">
<form method="post">
    <label>Nome: <input type="text" name="data[nome]"></label>
    <label>Email: <input type="text" name="data[email]"></label>
    <input type="hidden" name="data[produto_id]" value="{$produto.id}">
    <label><input type="submit" name="submit" value="Continuar"></label>

</form>

<div class="clearfix"></div>
{else}

<form id="frm" action="https://www.moip.com.br/PagamentoMoIP.do" method="post" target="_blank">
    <input type="hidden" name="id_carteira" value="schoolofnet">
    <input type="hidden" name="valor" value="{$data.valor}">
    <input type="hidden" name="nome" value="{$data.nome}">
    <input type="hidden" name="descricao" value="{$data.produto}">
    <input type="hidden" name="id_transacao" value="{$pedido_id}">
    <input type="hidden" name="pagador_email" value="{$data.email}">
</form>
<script>document.getElementById("frm").submit();</script>

{/if}