<html>
    <head>
        <title>Livraria School of Net</title>
        <meta http-equiv="Content-type" content="text/html;charset=utf-8" >
        <link rel="stylesheet" type="text/css" href="styles/style.css">
        <link rel="stylesheet" type="text/css" href="styles/frontend.css">
        <link rel="stylesheet" type="text/css" href="styles/form.css">

    </head>

    <body>

        <div id="barrinha"></div>
        <div id="estrutura">


            <div id="topo">
                <h1>ZfShop</h1>
                <div id="menu-superior">
                    <ul>
                        <li><a href="index.php">Home</a></li>
                    </ul>
                </div>
            </div>

            <div class="clearfix"></div>

            <div id="barra">
                <div id="menu-horizontal">
                    <ul>
                        <li><a href="index.php">Home</a></li>
                        {section name=i loop=$categorias}
                        <li><a href="index.php?categoria_id={$categorias[i].id}">{$categorias[i].nome}</a></li>
                        {/section}
                    </ul>
                </div>
            </div>

            <div id="conteudo">

                {include file=$content}

            </div>

            <div class="clearfix"></div>

        </div>
        <div id="footer">
            <p>Livraria SON - Todos os direitos reservados</p></div>
    </body>
</html>